routes:
  /rss/:
    template: rss
    content_type: text/xml

# static route tag "fun"
  /category/fun/guides-tips/:
    controller: channel
    filter: tag:fun+tag:guides-tips
    template: tag
    data: tag.guides-tips
  /category/fun/travel-destinations/:
    controller: channel
    filter: tag:fun+tag:travel-destinations
    template: tag
    data: tag.travel-destinations
  /category/fun/top-lists/:
    controller: channel
    filter: tag:fun+tag:top-lists
    template: tag
    data: tag.top-lists
  /category/fun/celebrities/:
    controller: channel
    filter: tag:fun+tag:celebrities
    template: tag
    data: tag.celebrities

# static route tag "business"
  /category/business/news/:
    controller: channel
    filter: tag:business+tag:news
    template: tag
    data: tag.news
  /category/business/company/:
    controller: channel
    filter: tag:business+tag:company
    template: tag
    data: tag.company
  /category/business/interviews/:
    controller: channel
    filter: tag:business+tag:interviews
    template: tag
    data: tag.interviews
  /category/business/media-and-press/:
    controller: channel
    filter: tag:business+tag:media-and-press
    template: tag
    data: tag.media-and-press

collections:
  /:
    permalink: /{year}/{month}/{slug}/
    template: index

taxonomies:
  tag: /category/{slug}/
  author: /author/{slug}/
